<?php

/**
 * Factory file is used to generate fake data for the database.
 * This file is automatically generated.
 * Data is generated using the database table structure.
 */

namespace Modules\Role\Database\factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class RoleFactory extends Factory
{
    protected $model = \Modules\Role\Entities\Role::class;

    public function definition(): array
    {
        return [
            "name" => $this->faker->name(),
        ];
    }
}
