<?php

/**
 * Seeder file is used to generate fake data for the database.
 * This file is automatically generated.
 * Seeder add the data to the database.
 */

namespace Modules\Gym\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class GymDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        // $this->call("OthersTableSeeder");
    }
}
