<?php

/**
 * Seeder file is used to generate fake data for the database.
 * This file is automatically generated.
 * Seeder add the data to the database.
 */

namespace Modules\Role\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class RoleDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        Model::unguard();

        $this->call(RoleTableSeeder::class);
    }
}
